package com.benimatic.twilightforest;

import net.minecraft.src.ModelQuadruped;
import net.minecraft.src.ModelRenderer;

public class ModelTwilightDeer extends ModelQuadruped {
	public ModelRenderer horn1a;
	public ModelRenderer horn1b;
	public ModelRenderer horn1c;
	public ModelRenderer horn1d;
	public ModelRenderer horn1e;
	public ModelRenderer horn1f;
	public ModelRenderer horn1g;
	public ModelRenderer horn1h;
	public ModelRenderer horn1i;
	public ModelRenderer horn1j;
	public ModelRenderer horn1k;
	public ModelRenderer horn2a;
	public ModelRenderer horn2b;
	public ModelRenderer horn2c;
	public ModelRenderer horn2d;
	public ModelRenderer horn2e;
	public ModelRenderer horn2f;
	public ModelRenderer horn2g;
	public ModelRenderer horn2h;
	public ModelRenderer horn2i;
	public ModelRenderer horn2j;
	public ModelRenderer horn2k;
	public ModelRenderer neck;
	public ModelRenderer nose;

	public ModelTwilightDeer() {
		super(12, 0.0F);
		this.head = new ModelRenderer(0, 5);
		this.head.addBox(-2.0F, -8.0F, -6.0F, 4, 6, 6, 0.0F);
		this.head.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.body = new ModelRenderer(36, 6);
		this.body.addBox(-4.0F, -10.0F, -7.0F, 6, 18, 8, 0.0F);
		this.body.setRotationPoint(1.0F, 5.0F, 2.0F);
		this.body.rotateAngleX = 1.570796F;
		this.leg1 = new ModelRenderer(0, 17);
		this.leg1.addBox(-3.0F, 0.0F, -2.0F, 2, 12, 3, 0.0F);
		this.leg1.setRotationPoint(0.0F, 12.0F, 9.0F);
		this.leg2 = new ModelRenderer(0, 17);
		this.leg2.addBox(-1.0F, 0.0F, -2.0F, 2, 12, 3, 0.0F);
		this.leg2.setRotationPoint(2.0F, 12.0F, 9.0F);
		this.leg3 = new ModelRenderer(0, 17);
		this.leg3.addBox(-3.0F, 0.0F, -3.0F, 2, 12, 3, 0.0F);
		this.leg3.setRotationPoint(0.0F, 12.0F, -5.0F);
		this.leg4 = new ModelRenderer(0, 17);
		this.leg4.addBox(-1.0F, 0.0F, -3.0F, 2, 12, 3, 0.0F);
		this.leg4.setRotationPoint(2.0F, 12.0F, -5.0F);
		this.neck = new ModelRenderer(10, 19);
		this.neck.addBox(-2.5F, -8.0F, -11.0F, 3, 9, 4, 0.0F);
		this.neck.setRotationPoint(1.0F, 5.0F, 2.0F);
		this.neck.rotateAngleX = 0.2443461F;
		this.nose = new ModelRenderer(52, 0);
		this.nose.addBox(-1.5F, -5.0F, -9.0F, 3, 3, 3, 0.0F);
		this.nose.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1a = new ModelRenderer(20, 0);
		this.horn1a.addBox(-3.0F, -10.0F, -2.0F, 2, 2, 2, 0.0F);
		this.horn1a.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1b = new ModelRenderer(20, 0);
		this.horn1b.addBox(-4.0F, -10.0F, -1.0F, 1, 1, 3, 0.0F);
		this.horn1b.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1c = new ModelRenderer(20, 0);
		this.horn1c.addBox(-5.0F, -11.0F, 1.0F, 1, 1, 5, 0.0F);
		this.horn1c.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1d = new ModelRenderer(20, 0);
		this.horn1d.addBox(-5.0F, -14.0F, 2.0F, 1, 4, 1, 0.0F);
		this.horn1d.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1e = new ModelRenderer(21, 0);
		this.horn1e.addBox(-6.0F, -17.0F, 3.0F, 1, 4, 1, 0.0F);
		this.horn1e.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1f = new ModelRenderer(20, 0);
		this.horn1f.addBox(-6.0F, -13.0F, 0.0F, 1, 1, 3, 0.0F);
		this.horn1f.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1g = new ModelRenderer(20, 0);
		this.horn1g.addBox(-6.0F, -14.0F, -3.0F, 1, 1, 4, 0.0F);
		this.horn1g.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1h = new ModelRenderer(21, 0);
		this.horn1h.addBox(-7.0F, -15.0F, -6.0F, 1, 1, 4, 0.0F);
		this.horn1h.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1i = new ModelRenderer(20, 0);
		this.horn1i.addBox(-6.0F, -16.0F, -9.0F, 1, 1, 4, 0.0F);
		this.horn1i.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1j = new ModelRenderer(25, 0);
		this.horn1j.addBox(-7.0F, -18.0F, -1.0F, 1, 5, 1, 0.0F);
		this.horn1j.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn1k = new ModelRenderer(28, 0);
		this.horn1k.addBox(-6.0F, -19.0F, -6.0F, 1, 5, 1, 0.0F);
		this.horn1k.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2a = new ModelRenderer(20, 0);
		this.horn2a.addBox(1.0F, -10.0F, -2.0F, 2, 2, 2, 0.0F);
		this.horn2a.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2b = new ModelRenderer(20, 0);
		this.horn2b.addBox(3.0F, -10.0F, -1.0F, 1, 1, 3, 0.0F);
		this.horn2b.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2c = new ModelRenderer(20, 0);
		this.horn2c.addBox(4.0F, -11.0F, 1.0F, 1, 1, 5, 0.0F);
		this.horn2c.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2d = new ModelRenderer(20, 0);
		this.horn2d.addBox(4.0F, -14.0F, 2.0F, 1, 4, 1, 0.0F);
		this.horn2d.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2e = new ModelRenderer(21, 0);
		this.horn2e.addBox(5.0F, -17.0F, 3.0F, 1, 4, 1, 0.0F);
		this.horn2e.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2f = new ModelRenderer(20, 0);
		this.horn2f.addBox(5.0F, -13.0F, 0.0F, 1, 1, 3, 0.0F);
		this.horn2f.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2g = new ModelRenderer(20, 0);
		this.horn2g.addBox(5.0F, -14.0F, -3.0F, 1, 1, 4, 0.0F);
		this.horn2g.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2h = new ModelRenderer(21, 0);
		this.horn2h.addBox(6.0F, -15.0F, -6.0F, 1, 1, 4, 0.0F);
		this.horn2h.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2i = new ModelRenderer(20, 0);
		this.horn2i.addBox(5.0F, -16.0F, -9.0F, 1, 1, 4, 0.0F);
		this.horn2i.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2j = new ModelRenderer(25, 0);
		this.horn2j.addBox(6.0F, -18.0F, -1.0F, 1, 5, 1, 0.0F);
		this.horn2j.setRotationPoint(0.0F, 4.0F, -7.0F);
		this.horn2k = new ModelRenderer(28, 0);
		this.horn2k.addBox(5.0F, -19.0F, -6.0F, 1, 5, 1, 0.0F);
		this.horn2k.setRotationPoint(0.0F, 4.0F, -7.0F);
	}

	public void render(float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(f, f1, f2, f3, f4, f5);
		this.setRotationAngles(f, f1, f2, f3, f4, f5);
		this.neck.render(f5);
		this.nose.render(f5);
		this.horn1a.render(f5);
		this.horn1b.render(f5);
		this.horn1c.render(f5);
		this.horn1d.render(f5);
		this.horn1e.render(f5);
		this.horn1f.render(f5);
		this.horn1g.render(f5);
		this.horn1h.render(f5);
		this.horn1i.render(f5);
		this.horn1j.render(f5);
		this.horn1k.render(f5);
		this.horn2a.render(f5);
		this.horn2b.render(f5);
		this.horn2c.render(f5);
		this.horn2d.render(f5);
		this.horn2e.render(f5);
		this.horn2f.render(f5);
		this.horn2g.render(f5);
		this.horn2h.render(f5);
		this.horn2i.render(f5);
		this.horn2j.render(f5);
		this.horn2k.render(f5);
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
		this.horn1a.rotateAngleY = this.head.rotateAngleY;
		this.horn1a.rotateAngleX = this.head.rotateAngleX;
		this.horn1b.rotateAngleY = this.head.rotateAngleY;
		this.horn1b.rotateAngleX = this.head.rotateAngleX;
		this.horn1c.rotateAngleY = this.head.rotateAngleY;
		this.horn1c.rotateAngleX = this.head.rotateAngleX;
		this.horn1d.rotateAngleY = this.head.rotateAngleY;
		this.horn1d.rotateAngleX = this.head.rotateAngleX;
		this.horn1e.rotateAngleY = this.head.rotateAngleY;
		this.horn1e.rotateAngleX = this.head.rotateAngleX;
		this.horn1f.rotateAngleY = this.head.rotateAngleY;
		this.horn1f.rotateAngleX = this.head.rotateAngleX;
		this.horn1g.rotateAngleY = this.head.rotateAngleY;
		this.horn1g.rotateAngleX = this.head.rotateAngleX;
		this.horn1h.rotateAngleY = this.head.rotateAngleY;
		this.horn1h.rotateAngleX = this.head.rotateAngleX;
		this.horn1i.rotateAngleY = this.head.rotateAngleY;
		this.horn1i.rotateAngleX = this.head.rotateAngleX;
		this.horn1j.rotateAngleY = this.head.rotateAngleY;
		this.horn1j.rotateAngleX = this.head.rotateAngleX;
		this.horn1k.rotateAngleY = this.head.rotateAngleY;
		this.horn1k.rotateAngleX = this.head.rotateAngleX;
		this.horn2a.rotateAngleY = this.head.rotateAngleY;
		this.horn2a.rotateAngleX = this.head.rotateAngleX;
		this.horn2b.rotateAngleY = this.head.rotateAngleY;
		this.horn2b.rotateAngleX = this.head.rotateAngleX;
		this.horn2c.rotateAngleY = this.head.rotateAngleY;
		this.horn2c.rotateAngleX = this.head.rotateAngleX;
		this.horn2d.rotateAngleY = this.head.rotateAngleY;
		this.horn2d.rotateAngleX = this.head.rotateAngleX;
		this.horn2e.rotateAngleY = this.head.rotateAngleY;
		this.horn2e.rotateAngleX = this.head.rotateAngleX;
		this.horn2f.rotateAngleY = this.head.rotateAngleY;
		this.horn2f.rotateAngleX = this.head.rotateAngleX;
		this.horn2g.rotateAngleY = this.head.rotateAngleY;
		this.horn2g.rotateAngleX = this.head.rotateAngleX;
		this.horn2h.rotateAngleY = this.head.rotateAngleY;
		this.horn2h.rotateAngleX = this.head.rotateAngleX;
		this.horn2i.rotateAngleY = this.head.rotateAngleY;
		this.horn2i.rotateAngleX = this.head.rotateAngleX;
		this.horn2j.rotateAngleY = this.head.rotateAngleY;
		this.horn2j.rotateAngleX = this.head.rotateAngleX;
		this.horn2k.rotateAngleY = this.head.rotateAngleY;
		this.horn2k.rotateAngleX = this.head.rotateAngleX;
		this.nose.rotateAngleY = this.head.rotateAngleY;
		this.nose.rotateAngleX = this.head.rotateAngleX;
	}
}
