#Minecraft server properties
#Wed Sep 23 12:14:16 CEST 2026
allow-nether=true
world-theme=normal
level-name=world
allow-flight=false
server-port=25565
level-type=DEFAULT
level-seed=
server-ip=
world-size=normal
white-list=false
spawn-animals=true
online-mode=false
pvp=true
layered-sand=true
max-players=20
spawn-monsters=true
generate-structures=true
view-distance=10
