package net.minecraft.src;

public class AetherRecipes {
	public AetherRecipes() {
		ModLoader.AddRecipe(new ItemStack(AetherItems.PickHolystone, 1), new Object[]{"ZZZ", " Y ", " Y ", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.AxeHolystone, 1), new Object[]{"ZZ", "ZY", " Y", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ShovelHolystone, 1), new Object[]{"Z", "Y", "Y", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.SwordHolystone, 1), new Object[]{"Z", "Z", "Y", 'Z', AetherBlocks.Holystone, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.PickZanite, 1), new Object[]{"ZZZ", " Y ", " Y ", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.AxeZanite, 1), new Object[]{"ZZ", "ZY", " Y", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ShovelZanite, 1), new Object[]{"Z", "Y", "Y", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.SwordZanite, 1), new Object[]{"Z", "Z", "Y", 'Z', AetherItems.Zanite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.PickGravitite, 1), new Object[]{"ZZZ", " Y ", " Y ", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.AxeGravitite, 1), new Object[]{"ZZ", "ZY", " Y", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ShovelGravitite, 1), new Object[]{"Z", "Y", "Y", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.SwordGravitite, 1), new Object[]{"Z", "Z", "Y", 'Z', AetherBlocks.EnchantedGravitite, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.PickSkyroot, 1), new Object[]{"ZZZ", " Y ", " Y ", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.AxeSkyroot, 1), new Object[]{"ZZ", "ZY", " Y", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ShovelSkyroot, 1), new Object[]{"Z", "Y", "Y", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.SwordSkyroot, 1), new Object[]{"Z", "Z", "Y", 'Z', AetherBlocks.Plank, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.Bucket, 1, 0), new Object[]{"Z Z", " Z ", 'Z', AetherBlocks.Plank});
		ModLoader.AddRecipe(new ItemStack(AetherItems.Stick, 4), new Object[]{"#", "#", '#', AetherBlocks.Plank});
		ModLoader.AddRecipe(new ItemStack(Block.workbench, 1), new Object[]{"UU", "UU", 'U', AetherBlocks.Plank});
		ModLoader.AddRecipe(new ItemStack(AetherBlocks.AmbrosiumTorch, 2), new Object[]{" Z", " Y", 'Z', AetherItems.AmbrosiumShard, 'Y', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(AetherItems.Dart, 1, 0), new Object[]{"X", "Z", "Y", 'X', AetherItems.GoldenAmber, 'Z', AetherItems.Stick, 'Y', Item.feather});
		ModLoader.AddRecipe(new ItemStack(AetherItems.Dart, 8, 1), new Object[]{"XXX", "XZX", "XXX", 'X', new ItemStack(AetherItems.Dart, 1, 0), 'Z', new ItemStack(AetherItems.Bucket, 1, 2)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.WhiteCape, 1), new Object[]{"XX", "XX", "XX", 'X', new ItemStack(Block.cloth, 1, 0)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.RedCape, 1), new Object[]{"XX", "XX", "XX", 'X', new ItemStack(Block.cloth, 1, 14)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.BlueCape, 1), new Object[]{"XX", "XX", "XX", 'X', new ItemStack(Block.cloth, 1, 11)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.BlueCape, 1), new Object[]{"XX", "XX", "XX", 'X', new ItemStack(Block.cloth, 1, 3)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.BlueCape, 1), new Object[]{"XX", "XX", "XX", 'X', new ItemStack(Block.cloth, 1, 9)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.YellowCape, 1), new Object[]{"XX", "XX", "XX", 'X', new ItemStack(Block.cloth, 1, 4)});
		ModLoader.AddRecipe(new ItemStack(AetherBlocks.Incubator, 1), new Object[]{"XXX", "XZX", "XXX", 'X', AetherBlocks.Holystone, 'Z', AetherBlocks.AmbrosiumTorch});
		ModLoader.AddRecipe(new ItemStack(AetherBlocks.Freezer, 1), new Object[]{"XXX", "XZX", "YYY", 'X', AetherBlocks.Holystone, 'Z', AetherBlocks.Icestone, 'Y', AetherBlocks.Plank});
		ModLoader.AddRecipe(new ItemStack(AetherBlocks.ZaniteBlock, 1), new Object[]{"XX", "XX", 'X', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.DartShooter, 1), new Object[]{"X", "X", "Y", 'X', AetherBlocks.Plank, 'Y', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.CloudParachute, 1), new Object[]{"UU", "UU", 'U', new ItemStack(AetherBlocks.Aercloud, 0)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.CloudParachuteGold, 1), new Object[]{"UU", "UU", 'U', new ItemStack(AetherBlocks.Aercloud, 2)});
		ModLoader.AddRecipe(new ItemStack(Item.saddle, 1), new Object[]{"XXX", "XZX", 'X', Item.leather, 'Z', Item.silk});
		ModLoader.AddRecipe(new ItemStack(AetherItems.NatureStaff, 1), new Object[]{"Y", "X", 'X', AetherItems.Stick, 'Y', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GravititeHelmet, 1), new Object[]{"XXX", "X X", 'X', AetherBlocks.EnchantedGravitite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GravititeBodyplate, 1), new Object[]{"X X", "XXX", "XXX", 'X', AetherBlocks.EnchantedGravitite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GravititePlatelegs, 1), new Object[]{"XXX", "X X", "X X", 'X', AetherBlocks.EnchantedGravitite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GravititeBoots, 1), new Object[]{"X X", "X X", 'X', AetherBlocks.EnchantedGravitite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZaniteHelmet, 1), new Object[]{"XXX", "X X", 'X', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZaniteChestplate, 1), new Object[]{"X X", "XXX", "XXX", 'X', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZaniteLeggings, 1), new Object[]{"XXX", "X X", "X X", 'X', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZaniteBoots, 1), new Object[]{"X X", "X X", 'X', AetherItems.Zanite});
		ModLoader.AddShapelessRecipe(new ItemStack(AetherItems.DartShooter, 1, 1), new Object[]{new ItemStack(AetherItems.DartShooter, 1, 0), AetherItems.AechorPetal});
		ModLoader.AddShapelessRecipe(new ItemStack(AetherItems.Zanite, 4), new Object[]{AetherBlocks.ZaniteBlock});
		ModLoader.AddShapelessRecipe(new ItemStack(Item.dyePowder, 2, 5), new Object[]{AetherBlocks.PurpleFlower});
		ModLoader.AddRecipe(new ItemStack(Block.chest, 1), new Object[]{"PPP", "P P", "PPP", 'P', AetherBlocks.Plank});
		ModLoader.AddRecipe(new ItemStack(Item.doorWood), new Object[]{"PP", "PP", "PP", 'P', AetherBlocks.Plank});
		ModLoader.AddRecipe(new ItemStack(Block.fence, 2), new Object[]{"SSS", "SSS", 'S', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(Block.ladder, 4), new Object[]{"S S", "SSS", "S S", 'S', AetherItems.Stick});
		ModLoader.AddRecipe(new ItemStack(Block.jukebox), new Object[]{"PPP", "PGP", "PPP", 'P', AetherBlocks.Plank, 'G', AetherBlocks.EnchantedGravitite});
		ModLoader.AddRecipe(new ItemStack(AetherBlocks.Plank, 4), new Object[]{"L", 'L', AetherBlocks.Log});
		ModLoader.AddRecipe(new ItemStack(AetherBlocks.Enchanter), new Object[]{"HHH", "HZH", "HHH", 'H', AetherBlocks.Holystone, 'Z', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.CloudParachute), new Object[]{"CC", "CC", 'C', new ItemStack(AetherBlocks.Aercloud, 1, 0)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.CloudParachuteGold), new Object[]{"CC", "CC", 'C', new ItemStack(AetherBlocks.Aercloud, 1, 2)});
		ModLoader.AddRecipe(new ItemStack(AetherItems.LeatherGlove), new Object[]{"C C", 'C', Item.leather});
		ModLoader.AddRecipe(new ItemStack(AetherItems.IronGlove), new Object[]{"C C", 'C', Item.ingotIron});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GoldGlove), new Object[]{"C C", 'C', Item.ingotGold});
		ModLoader.AddRecipe(new ItemStack(AetherItems.DiamondGlove), new Object[]{"C C", 'C', Item.diamond});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZaniteGlove), new Object[]{"C C", 'C', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GravititeGlove), new Object[]{"C C", 'C', AetherBlocks.EnchantedGravitite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.IronRing), new Object[]{" C ", "C C", " C ", 'C', Item.ingotIron});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GoldRing), new Object[]{" C ", "C C", " C ", 'C', Item.ingotGold});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZaniteRing), new Object[]{" C ", "C C", " C ", 'C', AetherItems.Zanite});
		ModLoader.AddRecipe(new ItemStack(AetherItems.IronPendant), new Object[]{"SSS", "S S", " C ", 'S', Item.silk, 'C', Item.ingotIron});
		ModLoader.AddRecipe(new ItemStack(AetherItems.GoldPendant), new Object[]{"SSS", "S S", " C ", 'S', Item.silk, 'C', Item.ingotGold});
		ModLoader.AddRecipe(new ItemStack(AetherItems.ZanitePendant), new Object[]{"SSS", "S S", " C ", 'S', Item.silk, 'C', AetherItems.Zanite});
	}
}
